Error when dimension of stack differs
stackedobs has the dimensions [stacks, env_obs, stacks]... In every step we should we be updating only the last stack, right? So we should update last instance of stack self.stackedobs[..., -1] = obs
Otherwise you get errors like:
ValueError: could not broadcast input array from shape (16,4) into shape (16,4,4)